# Configuration for sam2

# NOTE: Remember to update checkpoint and model together
model_type = "vit_b"
_checkpoint_path = "checkpoints/sam2/sam_vit_b_01ec64.pth"

# Mask generation configuration
[model_params]
points_per_side = 16  # Only one of points_per_side and point_grids allowed
# point_grids = [32, 16, 8, 4]  # Only one of points_per_side and point_grids allowed
points_per_batch = 64
pred_iou_thresh = 0.88
stability_score_thresh = 0.92
stability_score_offset = 1.0
box_nms_thresh = 0.6
crop_n_layers = 0
crop_nms_thresh = 0.85
crop_overlap_ratio = 0.4
crop_n_points_downscale_factor = 1
min_mask_region_area = 1000
output_mode = "binary_mask"