# MongoDB connection configuration
_database_template = "iris_{env}_{shop_name}"  # Template for database names with environment identifier

# Collections
image_metadata_collection = "image_metadata"
product_collection = "products"
scraping_progress_collection = "scraping_progress"