# Qdrant connection configuration
url="https://faa8f550-ff00-4890-b04e-1151b28d57a4.eu-west-2-0.aws.cloud.qdrant.io:6333"

embedding_dim = 512
_collection_template = "iris_{env}_{shop_name}_{collection_name}"
product_collection = 'products'
image_collection = 'images'
localization_collection = 'localizations'
