# Configuration for sam2

# NOTE: Remember to update checkpoint and model together
model_type = "vit_b"
_checkpoint_path = "checkpoints/sam_vit_b_01ec64.pth"
apply_postprocessing = false

# Mask generation configuration
[mask_generator_params]
points_per_side = 32  # Only one of points_per_side and point_grids allowed
points_per_batch = 64
pred_iou_thresh = 0.88
stability_score_thresh = 0.95
stability_score_offset = 1.0
box_nms_thresh = 0.7
crop_n_layers = 0
crop_nms_thresh = 0.7
crop_overlap_ratio = 0.341
crop_n_points_downscale_factor = 1
# point_grids = [32, 16, 8, 4]  # Only one of points_per_side and point_grids allowed
min_mask_region_area = 0
output_mode = "binary_mask"