# Base configuration for segmentation pipeline
[base]
model_checkpoint = "checkpoints/sam2.1_hiera_large.pt"
model_config = "configs/sam2.1/sam2.1_hiera_l.yaml"

# Mask generation configuration
[generation]
points_per_side = 8
points_per_batch = 128
pred_iou_thresh = 0.95
stability_score_thresh = 0.95
stability_score_offset = 0.7
crop_n_layers = 1
box_nms_thresh = 0.95
crop_n_points_downscale_factor = 2
min_mask_region_area = 100.0
use_m2m = false

# Clothing detection configuration
[clothing_detection]
min_aspect_ratio = 0.5  # Minimum aspect ratio for clothing items
max_aspect_ratio = 3.0  # Maximum aspect ratio for clothing items
min_area_ratio = 0.01   # Minimum area ratio relative to image size
max_area_ratio = 0.5    # Maximum area ratio relative to image size 