# Base configuration
environment = "demo"  # Current environment (dev, test, prod) 
device = "cpu"  # Preferred device to compute on (cuda, cpu, or mps)

# Config file paths
config_dir = "configs/"
[_config_paths]
shop_config_path = "data_pipeline/shops/nikolaj_storm.toml"
mongodb_config_path = "data_pipeline/mongodb.toml"
image_store_config_path = "data_pipeline/image_store.toml"
qdrant_config_path = "data_pipeline/qdrant.toml"
scraper_config_path = "data_pipeline/scraper.toml"
clip_config_path = "embedding_pipeline/clip.toml"
embeddingdb_config_path = "embedding_pipeline/database.toml"
localization_config_path = "localization_pipeline/localization.toml"
