# Pas Normal Studios configuration
base_url = "https://nikolajstorm.com/"

[image_selectors]
images = '''div.elementor.elementor-8061.elementor-location-single.product > div > div > div.elementor-element.elementor-element-c344227.e-flex.e-con-boxed.e-con.e-child > div > div > div > div > div > div.woocommerce-product-gallery__wrapper img[data-large_image]'''

[metadata_selectors]
title = '''div.elementor.elementor-8061.elementor-location-single.product > div > div > div.elementor-element.elementor-element-3500d0b.e-flex.e-con-boxed.e-con.e-child > div > div.elementor-element.elementor-element-e676599.elementor-widget.elementor-widget-woocommerce-product-title.elementor-page-title.elementor-widget-heading > div > h1'''
price = '''div.elementor.elementor-8061.elementor-location-single.product > div > div > div.elementor-element.elementor-element-3500d0b.e-flex.e-con-boxed.e-con.e-child > div > div.elementor-element.elementor-element-7244709.elementor-widget.elementor-widget-woocommerce-product-price > div > p > span > span > bdi'''
description = '''div.elementor.elementor-8061.elementor-location-single.product > div > div > div.elementor-element.elementor-element-3500d0b.e-flex.e-con-boxed.e-con.e-child > div > div.elementor-element.elementor-element-97fb32d.elementor-widget.elementor-widget-woocommerce-product-short-description > div > div'''

[scraper_overrides]
rate_limit = 0.0
pagination_link = "a[href*='/page/']"
product_link = "a[href*='/webshop/']"
category_link = "a[href*='/vare-kategori/']"
