# Pas Normal Studios configuration
shop_name = "pas_normal_studios"
base_url = "https://pasnormalstudios.com/dk"

[image_selectors]
images = '''body > div.flex.min-h-screen.flex-col > main > div > div > div:nth-child(1) > section.block-wrapper.page-offset-notification.relative.bg-\[\#f1f1f1\].lg\:h-screen.lg\:pt-0 > div.relative.transition-all.lg\:h-screen > div.relative.hidden.lg\:block.h-full img[class*="aspect-[inherit]"]'''

[metadata_selectors]
title = '''body > div.flex.min-h-screen.flex-col > main > div > div > div:nth-child(1) > section.block-wrapper.page-offset-notification.relative.bg-\[\#f1f1f1\].lg\:h-screen.lg\:pt-0 > div.absolute.bottom-\[50px\].right-\[50px\].z-\[5\].hidden.max-w-\[365px\].bg-white.p-6.lg\:block > div > div.text-xl.font-medium.leading-5'''
price = '''body > div.flex.min-h-screen.flex-col > main > div > div > div:nth-child(1) > section.block-wrapper.page-offset-notification.relative.bg-\[\#f1f1f1\].lg\:h-screen.lg\:pt-0 > div.absolute.bottom-\[50px\].right-\[50px\].z-\[5\].hidden.max-w-\[365px\].bg-white.p-6.lg\:block > div > div.hidden.md\:block > div > div > button > div > div'''
color = '''body > div.flex.min-h-screen.flex-col > main > div > div > div:nth-child(1) > section.block-wrapper.page-offset-notification.relative.bg-\[\#f1f1f1\].lg\:h-screen.lg\:pt-0 > div.absolute.bottom-\[50px\].right-\[50px\].z-\[5\].hidden.max-w-\[365px\].bg-white.p-6.lg\:block > div > button > div > div.flex.items-center.gap-1 > span'''
description = '''body > div.flex.min-h-screen.flex-col > main > div > div > div:nth-child(1) > section.block-wrapper.page-offset-notification.relative.bg-\[\#f1f1f1\].lg\:h-screen.lg\:pt-0 > div.absolute.bottom-\[50px\].right-\[50px\].z-\[5\].hidden.max-w-\[365px\].bg-white.p-6.lg\:block > div > div:nth-child(4) > div > div > p'''

[scraper_overrides]
rate_limit = 0.0

[scraper_overrides.patterns]
collection = "/collections/.+"
pagination = "/page/\\d+"