# Configuration for the overarching object localization pipeline

# Remember to change model_type and model_config if you are using a different model
model_type = "yolo"
model_config = "localization_pipeline/yolo.toml"